---
title: "hypoxia and stage"
author: "Rebecca Hoyd"
date: "11/2/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

One should read in the table 1 inputs to recreate the dataset used in this plot. 

# Load data

```{r}
orien.buffa <- read.csv("../data/TME_calculated-signatures.csv", stringsAsFactors = F)

radiation <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_Radiation_V4.csv", stringsAsFactors = F)
Linkage <- read_excel("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210707_ClinicalMolLinkage_V4_as-in-drake.xlsx") %>% rename("AvatarKey" = "ORIENAvatarKey")

clin_diag <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_Diagnosis_V4.csv")
clin_vit <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_VitalStatus_V4.csv")
clin_pat <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_PatientMaster_V4.csv")
clin.bmi <- read.csv("/fs/ess/PAS1695/projects/exorien/data/clinical/20PRJ060OSU_20210712_PhysicalAssessment_V4.csv") %>%
  group_by(AvatarKey) %>%
  filter(AgeAtPhysicalExam == max(AgeAtPhysicalExam))
```

```{r define radiation}
rad <- inner_join(Linkage,radiation, by = "AvatarKey")%>%
  rename("agec" = "Age At Specimen Collection","ager" = "AgeAtRadiationStart",
         "PM" = "Primary/Met", "Dose" = "RadDose", "Cancer" = "TCGA.code",
         "flag" = "RadiationTherapyInd", "sample" = "RNASeq")%>%
  mutate(ager = ifelse(grepl("Age", ager), 90, 
                       ifelse(grepl("Unknown",ager),0, ager)),
         agec = ifelse(grepl("Age", agec), 90, agec),
         agec = as.numeric(agec),
         r2c = abs(as.numeric(ager)-as.numeric(agec)),
         Rad_status = ifelse(grepl("No", flag), "No",
                      ifelse(grepl("Mig", flag)|grepl("Unk", Dose), "Unknown", "Yes")),
         Dose = ifelse(grepl("Unknown", Dose),0,
                       ifelse(as.numeric(Dose) > 8887, NA, as.numeric(Dose))))%>%
  select(AvatarKey, sample, agec, Cancer,PM, r2c, Rad_status, Dose,flag)%>%
  group_by(AvatarKey)%>%
  # filter(PM == "Primary")%>%
  arrange(r2c)%>%
  slice_head()%>%
  ungroup()%>%
  rename("Age" = "agec")

surv <- Linkage %>%
  select(AvatarKey, RNASeq, `Age At Specimen Collection`) %>%
  left_join(clin_vit) %>%
  mutate(AgeAtFirstContact = as.numeric(ifelse(grepl("o", `Age At Specimen Collection`),
                                               NA, `Age At Specimen Collection`)),
         AgeAtLastContact = as.numeric(ifelse(grepl("o", AgeAtLastContact), NA, AgeAtLastContact)),
         YearsToLC = AgeAtLastContact - AgeAtFirstContact,
         OS_days = YearsToLC*365.25,
         vital.status = ifelse(VitalStatus == "Dead", 1, 0),
         sample = RNASeq) %>%
  select(AvatarKey,sample, OS_days, vital.status)

diag <- clin_diag %>%
  select(AvatarKey, ClinGroupStage) %>%
  mutate(Stage = case_when(grepl("0", ClinGroupStage) ~ "0",
                           ClinGroupStage %in% c("I", "IA", "IA1", "IA2", "IA3", "IB", "IB1") ~ "I",
                           ClinGroupStage %in% c("II", "IIA", "IIB", "IIC") ~ "II",
                           ClinGroupStage %in% c("III", "IIIA", "IIIB", "IIIC") ~ "III",
                           grepl("IV", ClinGroupStage) ~ "IV",
                           .default = "Unknown"
                           ),
         Stage = fct_relevel(Stage, "Unknown"),
         stagecode = as.numeric(Stage)
         ) %>%
  group_by(AvatarKey) %>%
  filter(stagecode == max(stagecode)) %>%
  ungroup()

orien.allvars <- rad %>%
  filter(Cancer %in% c("READ", "COAD")) %>%
  # select(AvatarKey, sample, Rad_status) %>%
  left_join(orien.buffa) %>%
  # mutate(Buffa = ifelse(buffa.score > median(buffa.score), "High", "Low"),
  #        Buffa = fct_relevel(Buffa, "Low")) %>%
  # select(AvatarKey, sample, Buffa) %>%
  left_join(surv) %>%
  left_join(diag) %>%
  left_join(clin_pat) %>%
  left_join(clin.bmi)
```

# Plot

```{r}
orien.allvars %>%
  ggplot(aes(x = Stage, y = buffa.score)) +
  geom_boxplot() +
  labs(y = "Buffa hypoxia score") +
  theme_bw()

ggsave("../figures/boxplot_hypoxia-stage.png")
```

```{r}
orien.allvars %>%
  ggplot(aes(x = Sex, y = buffa.score)) +
  geom_boxplot() +
  labs(y = "Buffa hypoxia score") +
  theme_bw()

ggsave("../figures/boxplot_hypoxia-sex.png")
```