---
title: "plot normal tissue buffa"
author: "Caroline Wheeler"
date: "8/4/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(colorspace)
```

read in buffa
```{r}
buffa <- read.csv("../data/GTEx_buffa-scores.csv")
clin.samps <- read.delim("../data/GTEx_clinical-supp.txt")
```

# rename adjacent normal tissue
```{r}
buffa <- buffa %>%
  mutate(source = ifelse(source %in% c("blca", "brca", "cesc", "chol", "coad",
                                       "esca", "hnsc", "kich", "kirc", "kirp", "lihc",
                                       "luad", "lusc", "prad", "read", "stad", "thca", "ucec"),
                         paste0("adj.norm-", source), source),
         barcodes.short = str_sub(sample, 1,12)) %>%
  filter(barcodes.short %in% clin.samps$PATIENT_ID | source == "colon")
```

# Calculate the mean buffa for ordering purposes
```{r}
mean.buffa <- buffa %>%
  group_by(source) %>%
  summarize(mean = mean(buffa.score)) %>%
  mutate(`Buffa Category` = if_else(mean > 0,
                             true = "HB",
                             false = "LB")) %>%
  mutate(source = fct_reorder(source, mean)) %>%
  ungroup() 
```

```{r}
comb.ord <- buffa %>%
  left_join(mean.buffa) %>%
  mutate(source = fct_reorder(source, -mean))
```


# Colon alone

```{r}
col <- comb.ord %>%
  filter(source %in% c("colon", "coad-tumor", "read-tumor", "adj.norm-coad", "adj.norm-read")) %>%
  mutate(source = case_when(source == "colon" ~ "Colon",
                            source == "coad-tumor" ~ "COAD",
                            source == "read-tumor" ~ "READ",
                            source == "adj.norm-coad" ~ "Adjacent normal\n(COAD)",
                            source == "adj.norm-read" ~"Adjacent normal\n(READ)"),
         source = fct_reorder(source, -mean))

col %>%
  ggplot(aes(y = buffa.score, x = source)) +
  gghalves::geom_half_point(
    aes(color = source),
    range_scale = .4, 
    ## add some transparency
    alpha = .3,
    side = "l",
    show.legend = FALSE
  ) +
  gghalves::geom_half_boxplot(
    aes(
      # color = cancer,
      color = source,
    ),
    side = "l",
    width = 0.3,
    show.legend = FALSE
  ) +
  ggdist::stat_halfeye(
    aes(
      color = source,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1),
    show.legend = FALSE
  ) +
  theme_bw() +
  coord_flip() +
  scale_color_viridis_d() +
  labs(y = "Buffa Hypoxia Score",
       x = "")
ggsave("../figures/raincloud_normalTumor_buffa_COLON.png", width = 3, height = 3)
```